name: Daily Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update commit counter
      run: |
        FILE="commit_count.md"
        if [ ! -f "$FILE" ]; then
          echo "Commit count: 1" > "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'Commit count: \K\d+' "$FILE")
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          echo "Commit count: $NEXT_COUNT" > "$FILE"
        fi

    - name: Commit and push
      run: |
        git config --global user.name "Mansoob E Zehra"
        git config --global user.email "149682728+MansoobeZahra@users.noreply.github.com"
        git add commit_count.md
        git commit -m "Daily auto commit — count updated"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MansoobeZahra/auto-commit-bot.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
