name: Daily Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  # runs daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python autocommit.py

      - name: Show Git Diff
        run: git diff --stat || true

      - name: Manual Commit and Push
        run: |
          git config user.name "Mansoob E Zehra"
          git config user.email "149682728+MansoobeZahra@users.noreply.github.com"
          git add .
          git commit -m "Daily auto commit from workflow" || echo "No changes to commit"
          git push
