name: Daily Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python autocommit.py

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit from workflow
          commit_user_name: Mansoob E Zehra
<<<<<<< HEAD
          commit_user_email: 149682728+MansoobeZahra@users.noreply.github.com
=======
          commit_user_email: 149682728+MansoobeZahra@users.noreply.github.com
>>>>>>> eb04db2cb0a27ed4afda3bc63b50f2a0470ec7c1
